name: Publish Docs

on:
  push:
    branches: [ master ]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build docs
        run: |
          cd packages/noco-doc
          npm install
          npm run generate


      - name: Pushes generated output
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source_file: 'packages/noco-doc/dist/'
          destination_repo: 'nocodb/noco-docs'
          destination_folder: 'docs'
          user_email: 'pranavxc@gmail.com'
          user_name: 'pranavxc'
          commit_message: 'Autorelease from github.com/nocodb/nocodb/packages/noco-doc'